version: "3"

services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-container
    image: express-image
    ports:
      - "3001:3001"
    env_file:
      - ./code-editor-server/.env.prod
  db:
    image: "postgres:latest"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=team1
      - POSTGRES_PASSWORD=bread
      - POSTGRES_DB=code_editor
    ports:
      - "5432:5432"

volumes:
  pgdata: