# docker-compose.dev.yml
version: "3"

services:
  db:
    image: "postgres:latest"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=team1
      - POSTGRES_PASSWORD=bread
      - POSTGRES_DB=code_editor
    ports:
      - "5433:5432"

volumes:
  pgdata: